spring.application.name=transfer_service

# Cashmere API configuration
cashmere.api.token=d4cd4ac6f2f7efd9972f32f96f27c205d364023eb8df94ccbc5df5a36872e8ee
cashmere.api.base-url=https://cashmere.io/api/v2
