spring.application.name=transfer_service

# Cashmere API configuration
cashmere.api.token=16509d536a4338a71387914ae4853735db5c40db85be7a452ec07e48d2649425
cashmere.api.base-url=https://cashmere.io/api/v2

# Content API configuration
content.api.base-url=https://platform.hbsp.harvard.edu/hbp/api/content

# Github API configuration
github.api.base-url=https://git.harvardbusiness.org/api/v3
github.api.token=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

logging.file.name=./logs/application.log
logging.level.root=INFO

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
