spring.application.name=transfer_service

# Cashmere API configuration
cashmere.api.token=d4cd4ac6f2f7efd9972f32f96f27c205d364023eb8df94ccbc5df5a36872e8ee
cashmere.api.base-url=https://cashmere.io/api/v2

# Content API configuration
content.api.base-url=https://platform.hbsp.harvard.edu/hbp/api/content

# Github API configuration
github.api.base-url=https://git.harvardbusiness.org/api/v3
github.api.token=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

logging.file.name=./logs/application.log
logging.level.root=INFO

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
